FROM openjdk:22-jdk-bullseye

WORKDIR /usr/src/testapi
ARG allure_ver=2.24.0

COPY . .

# EXPOSE 9999 9999

RUN wget https://github.com/allure-framework/allure2/releases/download/2.24.0/allure-2.24.0.zip \
    && unzip allure-2.24.0.zip \
    && mv allure-2.24.0/ /usr/local/bin/allure-2.24.0 \
    && rm allure-2.24.0.zip \
    && mkdir logs report \
    && chmod +x /usr/src/testapi/start.sh 

ENV PATH="$PATH:/usr/local/bin/allure-2.24.0/bin"
# VOLUME [ "" ]

# CMD /usr/src/testapi/start.sh
