FROM openjdk:22-jdk-bullseye

WORKDIR /usr/src/testapi
ARG allure_ver=2.24.0

# =======
# ALLURE
# =======
RUN wget https://github.com/allure-framework/allure2/releases/download/2.24.0/allure-2.24.0.zip \
    && unzip allure-2.24.0.zip \
    && mv allure-2.24.0/ /usr/local/bin/allure-2.24.0 \
    && rm allure-2.24.0.zip \
    && mkdir logs report

ENV PATH="$PATH:/usr/local/bin/allure-2.24.0/bin"

